version: '3'
services:
    web:
        image: nginx:1.21.6
        container_name: nginx
        ports:
            - '127.0.0.1:${NGINX_PORT}:80'
        volumes:
            - ./api:/var/www/api
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
            - mariadb
        depends_on:
            - php
            - mariadb
    php:
        image: php:8.1.3-fpm
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./api:/var/www/api
        links:
            - mariadb
        depends_on:
            - mariadb
        working_dir: ./api:/var/www/api
    node:
        image: node:16.14.0
        volumes:
            - ./api:/var/www/api
        container_name: node
        working_dir: ./api:/var/www/api
        tty: true
    mariadb:
        image: mariadb:10.8.2
        container_name: mariadb
        command: ['--default-authentication-plugin=mysql_native_password']
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        ports:
            - '${MARIADB_PORT}:3306'
        volumes:
            - ./database:/var/lib/mysql